#pragma once

#include "CoreMinimal.h"
#include "Engine/Texture.h"
#include "TextureChannelPacker.h"

class UTexture2D;

DECLARE_LOG_CATEGORY_EXTERN(LogTexturePacker, Log, All);

/**
 * Shared utilities used by both the Pack tab (FTextureChannelPackerModule) and the
 * Unpack tab (FTextureChannelUnpacker). Kept in a namespace to avoid symbol clashes
 * with other modules in monolithic builds.
 */
namespace TextureChannelPackerUtils
{
    /** Resolution above which a memory-consumption warning dialog is shown before processing. */
    inline constexpr int32 LargeTextureWarningThreshold = 8192;

    /** Maximum supported texture dimension (DirectX 11 / OpenGL 4.1+ limit). */
    inline constexpr int32 MaxTextureDimension = 16384;

    /**
     * @brief Retrieves a localized message based on the current culture.
     *
     * Returns either the Japanese text (if the current culture is Japanese)
     * or the English text (for all other cultures).
     *
     * @param Key A unique identifier for the localization key (currently unused but good for future expansion).
     * @param EnglishText The text to display in English.
     * @param JapaneseText The text to display in Japanese.
     * @return FText The localized text.
     */
    FText GetLocalizedMessage(const FString& Key, const FString& EnglishText, const FString& JapaneseText);

    /**
     * @brief Displays a notification toast in the editor.
     *
     * @param Message The text message to display.
     * @param bSuccess If true, shows a success icon; otherwise, shows an error icon.
     */
    void ShowNotification(const FText& Message, bool bSuccess);

    /** Short single-letter label for a source channel (R/G/B/A) for compact UI. */
    FString SourceChannelToShortString(ESourceChannel Ch);

    /**
     * @brief Returns the byte offset of the requested channel within a BGRA8 pixel.
     *
     * BGRA8 lays out bytes as [B, G, R, A], so Red=2, Green=1, Blue=0, Alpha=3.
     */
    int32 GetBGRAChannelOffset(ESourceChannel Channel);

    /** Extracts the requested channel value from an FColor. */
    uint8 ExtractChannelFromFColor(const FColor& C, ESourceChannel Channel);

    /**
     * @brief Returns true for source formats that physically only carry one channel of data.
     *
     * For these formats, the channel selector is meaningless — the lone luminance value is
     * always used regardless of which output channel the user picks.
     */
    bool IsSingleChannelFormat(ETextureSourceFormat Format);

    /**
     * @struct FTextureRawData
     * @brief Holds raw texture data extracted from a UTexture2D.
     *
     * This struct is used to transfer texture data from the Game Thread (where UTexture2D is accessible)
     * to background threads for processing. It ensures thread safety by copying necessary data
     * (dimensions, format, raw bytes) beforehand.
     */
    struct FTextureRawData
    {
        TArray<uint8> RawData;
        int32 Width = 0;
        int32 Height = 0;
        ETextureSourceFormat Format = TSF_Invalid;
        FString TextureName;
        bool bIsValid = false;

        /**
         * User-facing error message if extraction failed.
         * Empty if no error occurred.
         */
        FText ErrorMessage;
    };

    /**
     * @struct FTextureProcessResult
     * @brief Represents the result of a texture processing operation.
     *
     * This struct contains the processed pixel data for a specific channel or an error message
     * if the operation failed. It is generated by background threads and consumed by the Game Thread.
     */
    struct FTextureProcessResult
    {
        TArray<uint8> ProcessedData;
        FText ErrorMessage;
        bool bSuccess = true;
    };

    /**
     * @brief Extracts raw pixel data from a UTexture2D on the Game Thread.
     *
     * This function accesses the platform-specific source data of a texture asset,
     * locks the mipmap to read raw bytes, and copies them into a thread-safe struct.
     * This MUST be called on the Game Thread.
     *
     * @param SourceTex The source UTexture2D asset.
     * @return FTextureRawData A struct containing the copied raw data and metadata.
     */
    FTextureRawData ExtractTextureSourceData(UTexture2D* SourceTex);

    /**
     * @brief Processes raw texture data to produce a single channel of output.
     *
     * This function handles resizing (using FImageUtils) and format conversion (e.g., extracting
     * the selected channel from BGRA/RGBA, or converting 16-bit grayscale to 8-bit).
     * This function is designed to be thread-safe and run in parallel tasks.
     *
     * @param Input The raw source data extracted from the input texture.
     * @param TargetWidth The target width for the output.
     * @param TargetHeight The target height for the output.
     * @param SourceChannel Which channel of the input to read (R/G/B/A). Ignored for single-channel formats.
     * @return FTextureProcessResult The processed single-channel 8-bit data.
     */
    FTextureProcessResult ProcessTextureSourceData(FTextureRawData& Input, int32 TargetWidth, int32 TargetHeight, ESourceChannel SourceChannel);
}
